name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: debugging
        if: ${{ github.ref == 'ref/head/master' && github.event_name != 'pull_request' }}
        run: echo "ref: ${{ github.ref }} ${{ github.ref == 'refs/pull/14/merge }} event_name: ${{ github.event_name }} ${{ github.event_name == 'pull_request' }}"

