name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build and Run Tests
        run: ./gradlew --stacktrace check
        
      - name: Deploy SNAPSHOT
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: ./script/deploy.sh snapshot
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
